apiVersion: argoproj.io/v1alpha1
metadata:
  name: openfaas
spec:
  destination:
    namespace: openfaas
    server: 'https://kubernetes.default.svc'
  source:
    path: chart/openfaas
    repoURL: 'https://github.com/openfaas/faas-netes'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
