Vagrant.configure("2") do |config|
  # Define variables for common values
  box_name = "generic/alpine318"
  memory_size = "2048"
  cpus_count = "3"
  synced_folder_path = "./confs"
  private_network_ip1 = "192.168.56.110"
  private_network_ip2 = "192.168.56.111"
  node_token_path = "/var/lib/rancher/k3s/server/node-token"
  kube_config_path = "/etc/rancher/k3s/k3s.yaml"
  k3s_install_command = "curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE='644' INSTALL_K3S_EXEC='--flannel-iface eth1'"
  
  config.vm.define "ablaamimS" do |master|
    master.vm.box = box_name
    master.vm.network "private_network", ip: private_network_ip1
    master.vm.hostname = "ablaamimS"
    master.vm.synced_folder synced_folder_path, "/vagrant", type: "virtualbox"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = memory_size
      vb.cpus = cpus_count
      vb.name = "ablaamimS"
    end

    master.vm.provision "shell", inline: <<-SHELL
      echo "Debugging message: Provisioning ablaamimS master node..."
      #{k3s_install_command} sh -
      sleep 10
      sudo chmod 644 #{kube_config_path}
      while [ ! -e #{node_token_path} ]; do
        sleep 2
      done
      sudo cat #{node_token_path}
      sudo cp #{node_token_path} /vagrant/
      sudo cp #{kube_config_path} /vagrant/
      echo "Debugging message: ablaamimS master node provisioning completed."
    SHELL
  end

  config.vm.define "ablaamimSW" do |node1|
    node1.vm.box = box_name
    node1.vm.hostname = "ablaamimSW"
    node1.vm.synced_folder synced_folder_path, "/vagrant", type: "virtualbox"
    node1.vm.network "private_network", ip: private_network_ip2
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = memory_size
      vb.cpus = cpus_count
      vb.name = "ablaamimSW"
    end

    node1.vm.provision "shell", inline: <<-SHELL
      echo "Debugging message: Provisioning ablaamimSW node..."
      #{k3s_install_command} K3S_URL=https://#{private_network_ip1}:6443 K3S_TOKEN=$(sudo cat /vagrant/node-token) sh -
      sleep 10
      echo "Debugging message: ablaamimSW node provisioning completed."
    SHELL
  end
end

