apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://gitlab.ablaamim.gitlab.io/root/inception-of-things.git
    targetRevision: HEAD
    path: ./app
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
