stages:
  - "deploy"

variables:
  ARGOCD_PASSWORD: 'MJQDErhH7GW0azBP'
  ARGOCD_ADDRESS: 'localhost:8080'

deploy-job:
  image: argoproj/argocd
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" #Run this job when manually triggered from gitlab.com
    - if: $CI_PIPELINE_SOURCE == "push" #Run this job after a git push if changes were made in app
      changes:
        - app/*
  script:
    - argocd login $ARGOCD_ADDRESS --username admin --password $ARGOCD_PASSWORD --insecure --grpc-web
    - argocd app sync will --grpc-web
    - echo "Repository successfully synchronized with running app!!"
~                                                                    
